spring.application.name=e_commerce

#erro message ??return to frontend, ?frontend??????error
server.error.include-message=always

#jap connect aws mysql db server
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://database-1.c5saseaqev9z.ap-southeast-1.rds.amazonaws.com:3306/e_commerce
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

#spring security connect firebase server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/fsse2510-project-jimmy

#spring boot connect redis online server
spring.data.redis.host=redis-11054.crce178.ap-east-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=11054
spring.data.redis.password=l4DE9RU3aKriVBBghUKOrO5PlA82d3IC
spring.data.redis.timeout=5000

# Redis Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true